apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx:psp:privileged
  namespace: wild-west
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: nginx
    namespace: wild-west

# imperative equivalent:
#  kubectl create sa nginx
#  kubectl create rolebinding nginx:psp:privileged \
#  --role=psp:privileged \
#  --serviceaccount=wild-west:nginx