apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  serviceName: stateful
  selector:
    matchLabels:
      run: stateful
  template:
    metadata:
      labels:
        run: stateful
    spec:
      containers:
        - image: nginx:1.17.2
          name: stateful
          securityContext: {}