kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-allow-nosqlclient-to-access-mongo
  namespace: production
spec:
  podSelector:
    matchLabels:
      role: mongodb
  ingress:
    - ports:
        - port: 27017
      from:
        - podSelector:
            matchLabels:
              run: nosqlclient
