kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-nginx-allow-internal-only
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      run: docker-sudo
  egress:
    - to:
        - namespaceSelector: {}